<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--- Program: lqcountrpts.cfm.cfm --->
<!--- By: JOHN R. PASTORI --->
<!--- Date Written: 01/13/2007 --->
<!--- Date in Production: 01/13/2007 --->
<!--- Module: LibQual Comments Count Reports --->
<!-- Last modified by John R. Pastori on 01/13/2007 using ColdFusion Studio. -->

<CFINCLUDE TEMPLATE = "../programsecuritycheck.cfm">

<!--- 
*************************************************************
* The following code displays the LibQual Comments Reports. *
*************************************************************
 --->

<CFOUTPUT>
	<table width="100%" align="center" BORDER="3">
		<tr align="center">
			<td align="center">
				<H1>LibQual Comments Count Reports
				<H2>#REPORTTITLE#<BR />
			<CFIF RECORDSSELECTED EQ 'YES'>
				#AGERANGECRITERIA# &nbsp;&nbsp; #DISCIPLINECRITERIA# &nbsp;&nbsp; #GENDERCRITERIA# &nbsp;&nbsp; #POSITIONCRITERIA#<BR />
				#LQGROUPCRITERIA# &nbsp;&nbsp; #LQSUBGROUPCRITERIA#
			<CFELSE>
				ALL RECORDS
			</CFIF>
			</h2></h1></td>
		</tr>
	</table>
	<table width="100%" align="center" BORDER="0">
		<tr>
<cfform action="/#application.type#apps/libqual/lqrptslookup.cfm?TYPE=#URL.TYPE#" METHOD="POST">
			<td align="LEFT"><input type="submit" value="Cancel" tabindex="1" /></td>
</cfform>
		</tr>
	<CFIF FORM.REPORTCHOICE GT 2>
		<tr>
			<th ALIGN="CENTER" COLSPAN="3"><H4>#ListLIBQUAL_Comments.RecordCount# LibQual Comment records were selected.</h4></th>
		</tr>
	</CFIF>
	</table>
</CFOUTPUT>

<CFIF FORM.REPORTCHOICE LT 3>
	<CFSET RECCOUNT = 0>
	<CFSET RECORDPERCENT = 0>
	<CFSET TOTRECCOUNT = 0>
	<table width="100%" align="LEFT" BORDER="0">
		<CFOUTPUT>
		<tr>
			<TH ALIGN="left">#GROUPTITLE#</TH>
			<TH ALIGN="RIGHT">Record Count</TH>
			<TH ALIGN="RIGHT">Precentage of 2048 Total Records</TH>
		</tr>
		</CFOUTPUT>

<CFOUTPUT query = "#client.QUERYNAME#">
		<CFSET client.LOOKUPFIELD = "LQC." & "#Evaluate('#client.QUERYFIELDNAME#')#">

	<cfquery name="SelectLIBQUAL_Comments" DATASOURCE="#application.type#LIBQUAL" BLOCKFACTOR="100">
		SELECT	LQC.COMMENTID, LQC.LIBQUALRECID, LQC.DATEENTERED, LQC.POSITIONID, P.POSITIONNAME, LQC.LIBQUALDISCIPLINEID,
				LQC.DISCIPLINEID, D.DISCIPLINENAME, LQC.AGERANGEID, AR.LIBQUALAGEID, AR.AGERANGENAME, LQC.GENDERID, G.GENDERNAME, LQC.COMMENTS,
				LQC.BUILDINGGROUP, LQC.BLD_ACCESSIBILITY, LQC.BLD_CLEANMAINT, LQC.BLD_ELECTOUTLETS,LQC.BLD_FURNITURE, LQC.BLD_GROUPSTUDY,
				LQC.BLD_HEATCOOL, LQC.BLD_HOURS, LQC.BLD_LIGHTING, LQC.BLD_QUIETSPACE, LQC.BLD_RESTROOMS, LQC.BLD_SAFETY, LQC.BLD_SIGNAGE,
				LQC.BLD_STUDYSPACE, LQC.COLLECTIONSGROUP, LQC.COL_MAINT, LQC.COL_ONLINE, LQC.COL_PERIODICALS, LQC.COL_PRINT, 
				LQC.POLICIESGROUP, LQC.POL_CELLPHONES, LQC.POL_EATDRINK, LQC.POL_FINES, LQC.POL_GENERAL, LQC.POL_NOISE, LQC.POL_SLEEPING,
				LQC.REPORTGROUP, LQC.BUDGET, LQC.RPT_CONFUSION, LQC.RPT_NEGATIVE, LQC.RPT_POSITIVE, LQC.SERVICEGROUP, LQC.SRV_CIRCUIT,
				LQC.SRV_CIRCDESK, LQC.SRV_COPYSRVCS, LQC.SRV_ECR, LQC.SRV_ELECTRONICREF, LQC.SRV_GOVTPUBS, LQC.SRV_HOURS, LQC.SRV_INSTREDOR,
				LQC.SRV_ILL, LQC.SRV_LIBRINTERACT,LQC.SRV_LINKPLUS, LQC.SRV_MEDIACNTR, LQC.SRV_CPMC, LQC.SRV_REFDESK, LQC.SRV_RBR,
				LQC.SRV_SCC, LQC.SRV_SPCOLL, LQC.SRV_STAFFINTERACT, LQC.SRV_STUDNTINTERACT, LQC.SRV_TELEPHONE, LQC.SRV_WEBOPACSRVC,
				LQC.TECHNOLOGYGROUP, LQC.TECH_COMPTECHGENRL, LQC.TECH_OTHERHW, LQC.TECH_OTHERLIBCOMP, LQC.TECH_PERCOMPLAB,
				LQC.TECH_PRINTING, LQC.TECH_REFCOMPLAB, LQC.TECH_REMOTEACCESS, LQC.TECH_RBRLAB, LQC.TECH_SCCLAB, LQC.CHECKEDBYID,
				CI.INITIALS, LQC.RECCHECKED
		FROM		LIBQUAL_COMMENTS LQC, LQPOSITIONS P, WEBRPTSMGR.DISCIPLINES D, LIBSHAREDDATAMGR.AGERANGES AR, LIBSHAREDDATAMGR.GENDER G, LQCHECKEDINITIALS CI
		WHERE	(LQC.COMMENTID > 0 AND
				LQC.POSITIONID = P.POSITIONID AND
				LQC.DISCIPLINEID = D.DISCIPLINEID AND
				LQC.AGERANGEID = AR.AGERANGEID AND
				LQC.GENDERID = G.GENDERID AND
				LQC.CHECKEDBYID = CI.CHECKEDINITID) AND (

		<CFIF #FORM.POSITIONID# GT 0>
			<CFIF IsDefined("FORM.NEGATEPOSITIONID")>
				NOT LQC.POSITIONID = #val(FORM.POSITIONID)# #LOGICANDOR#
			<CFELSE>
				LQC.POSITIONID = #val(FORM.POSITIONID)# #LOGICANDOR#
			</CFIF>
		</CFIF>

		<CFIF #FORM.DISCIPLINEID# GT 0>
			<CFIF IsDefined("FORM.NEGATEDISCIPLINEID")>
				NOT LQC.DISCIPLINEID = #val(FORM.DISCIPLINEID)# #LOGICANDOR#
			<CFELSE>
				LQC.DISCIPLINEID = #val(FORM.DISCIPLINEID)# #LOGICANDOR#
			</CFIF>
		</CFIF>

		<CFIF #FORM.AGERANGEID# GT 0>
			<CFIF IsDefined("FORM.NEGATEAGERANGEID")>
				NOT LQC.AGERANGEID = #val(FORM.AGERANGEID)# #LOGICANDOR#
			<CFELSE>
				LQC.AGERANGEID = #val(FORM.AGERANGEID)# #LOGICANDOR#
			</CFIF>
		</CFIF>

		<CFIF #FORM.GENDERID# GT 0>
			<CFIF IsDefined("FORM.NEGATEGENDERID")>
				NOT LQC.GENDERID = #val(FORM.GENDERID)# #LOGICANDOR#
			<CFELSE>
				LQC.GENDERID = #val(FORM.GENDERID)# #LOGICANDOR#
			</CFIF>
		</CFIF>

			<CFIF FORM.BUILDINGGROUP EQ 'YES'>
				LQC.BUILDINGGROUP = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_ACCESSIBILITY EQ 'YES'>
				LQC.BLD_ACCESSIBILITY = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_CLEANMAINT EQ 'YES'>
				LQC.BLD_CLEANMAINT = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_ELECTOUTLETS EQ 'YES'>
				LQC.BLD_ELECTOUTLETS = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_FURNITURE EQ 'YES'>
				LQC.BLD_FURNITURE = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_GROUPSTUDY EQ 'YES'>
				LQC.BLD_GROUPSTUDY= 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_HEATCOOL EQ 'YES'>
				LQC.BLD_HEATCOOL = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_HOURS EQ 'YES'>
				LQC.BLD_HOURS = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_LIGHTING EQ 'YES'>
				LQC.BLD_LIGHTING = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_QUIETSPACE EQ 'YES'>
				LQC.BLD_QUIETSPACE = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_RESTROOMS EQ 'YES'>
				LQC.BLD_RESTROOMS = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_SAFETY EQ 'YES'>
				LQC.BLD_SAFETY = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_SIGNAGE EQ 'YES'>
				LQC.BLD_SIGNAGE = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BLD_STUDYSPACE EQ 'YES'>
				LQC.BLD_STUDYSPACE = 'YES' #LOGICANDOR#
			</CFIF>

			<CFIF FORM.COLLECTIONSGROUP EQ 'YES'>
				LQC.COLLECTIONSGROUP = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.COL_MAINT EQ 'YES'>
				LQC.COL_MAINT = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.COL_ONLINE EQ 'YES'>
				LQC.COL_ONLINE = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.COL_PERIODICALS EQ 'YES'>
				LQC.COL_PERIODICALS = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.COL_PRINT EQ 'YES'>
				LQC.COL_PRINT = 'YES' #LOGICANDOR#
			</CFIF>

			<CFIF FORM.POLICIESGROUP EQ 'YES'>
				LQC.POLICIESGROUP = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.POL_CELLPHONES EQ 'YES'>
				LQC.POL_CELLPHONES = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.POL_EATDRINK EQ 'YES'>
				LQC.POL_EATDRINK = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.POL_FINES EQ 'YES'>
				LQC.POL_FINES = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.POL_GENERAL EQ 'YES'>
				LQC.POL_GENERAL = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.POL_NOISE EQ 'YES'>
				LQC.POL_NOISE = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.POL_SLEEPING EQ 'YES'>
				LQC.POL_SLEEPING = 'YES' #LOGICANDOR#
			</CFIF>

			<CFIF FORM.REPORTGROUP EQ 'YES'>
				LQC.REPORTGROUP = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.BUDGET EQ 'YES'>
				LQC.BUDGET = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.RPT_CONFUSION EQ 'YES'>
				LQC.RPT_CONFUSION = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.RPT_NEGATIVE EQ 'YES'>
				LQC.RPT_NEGATIVE = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.RPT_POSITIVE EQ 'YES'>
				LQC.RPT_POSITIVE = 'YES' #LOGICANDOR#
			</CFIF>

			<CFIF FORM.SERVICEGROUP EQ 'YES'>
				LQC.SERVICEGROUP = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_CIRCUIT EQ 'YES'>
				LQC.SRV_CIRCUIT = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_CIRCDESK EQ 'YES'>
				LQC.SRV_CIRCDESK = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_COPYSRVCS EQ 'YES'>
				LQC.SRV_COPYSRVCS = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_ECR EQ 'YES'>
				LQC.SRV_ECR = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_ELECTRONICREF EQ 'YES'>
				LQC.SRV_ELECTRONICREF = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_GOVTPUBS EQ 'YES'>
				LQC.SRV_GOVTPUBS = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_HOURS EQ 'YES'>
				LQC.SRV_HOURS = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_INSTREDOR EQ 'YES'>
				LQC.SRV_INSTREDOR = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_ILL EQ 'YES'>
				LQC.SRV_ILL = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_LIBRINTERACT EQ 'YES'>
				LQC.SRV_LIBRINTERACT = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_LINKPLUS EQ 'YES'>
				LQC.SRV_LINKPLUS = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_MEDIACNTR EQ 'YES'>
				LQC.SRV_MEDIACNTR = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_CPMC EQ 'YES'>
				LQC.SRV_CPMC = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_REFDESK EQ 'YES'>
				LQC.SRV_REFDESK = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_RBR EQ 'YES'>
				LQC.SRV_RBR = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_SCC EQ 'YES'>
				LQC.SRV_SCC = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_SPCOLL EQ 'YES'>
				LQC.SRV_SPCOLL = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_STAFFINTERACT EQ 'YES'>
				LQC.SRV_STAFFINTERACT = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_STUDNTINTERACT EQ 'YES'>
				LQC.SRV_STUDNTINTERACT = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_TELEPHONE EQ 'YES'>
				LQC.SRV_TELEPHONE = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.SRV_WEBOPACSRVC EQ 'YES'>
				LQC.SRV_WEBOPACSRVC = 'YES' #LOGICANDOR#
			</CFIF>

			<CFIF FORM.TECHNOLOGYGROUP EQ 'YES'>
				LQC.TECHNOLOGYGROUP = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.TECH_COMPTECHGENRL EQ 'YES'>
				LQC.TECH_COMPTECHGENRL = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.TECH_OTHERHW EQ 'YES'>
				LQC.TECH_OTHERHW = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.TECH_OTHERLIBCOMP EQ 'YES'>
				LQC.TECH_OTHERLIBCOMP = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.TECH_PERCOMPLAB EQ 'YES'>
				LQC.TECH_PERCOMPLAB = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.TECH_PRINTING EQ 'YES'>
				LQC.TECH_PRINTING = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.TECH_REFCOMPLAB EQ 'YES'>
				LQC.TECH_REFCOMPLAB = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.TECH_REMOTEACCESS EQ 'YES'>
				LQC.TECH_REMOTEACCESS = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.TECH_RBRLAB EQ 'YES'>
				LQC.TECH_RBRLAB = 'YES' #LOGICANDOR#
			</CFIF>
			<CFIF FORM.TECH_SCCLAB EQ 'YES'>
				LQC.TECH_SCCLAB = 'YES' #LOGICANDOR#
			</CFIF>

				#client.LOOKUPFIELD# = 'YES' AND
				LQC.COMMENTID #FINALTEST# 0)
		ORDER BY	#REPORTORDER#
	</cfquery>

	<CFSET COMPAREHEADER = #Evaluate("#FIELDNAME#")#>
	<CFIF REPORTHEADER NEQ #COMPAREHEADER#>
		<CFIF #RECCOUNT# GT 0>
			<CFSET RECORDPERCENT = ((#RECCOUNT#/2048)*100)>
		<TR>
			<TD ALIGN="LEFT">#REPORTHEADER#</td>
			<TD ALIGN="RIGHT">#RECCOUNT#</td>
			<TD ALIGN="RIGHT">
				#NUMBERFORMAT(RECORDPERCENT, '__.__')#%
				<CFSET RECCOUNT = 0>
				<CFSET RECORDPERCENT = 0>
				<CFSET REPORTHEADER = #COMPAREHEADER#>
			</td>
		</TR>
		</CFIF>
	</CFIF>
	<cfloop query = "SelectLIBQUAL_Comments">
		<CFSET RECCOUNT = #RECCOUNT# + 1>
		<CFSET TOTRECCOUNT = #TOTRECCOUNT# + 1>
	</cfloop>

</CFOUTPUT>
<CFELSE>

	<CFOUTPUT>

	<CFSET COMPAREHEADER = #Evaluate("#FIELDNAME#")#>
	<CFSET REPORTHEADER = #COMPAREHEADER#>
	<CFSET RECCOUNT = 0>
	<CFSET RECORDPERCENT = 0>
	<table width="100%" align="LEFT" BORDER="0">
		<tr>
			<TH ALIGN="left">#GROUPTITLE#</TH>
			<TH ALIGN="RIGHT">Record Count</TH>
			<TH ALIGN="RIGHT">Precentage of 2048 Total Records</TH>
		</tr>
<cfloop query = "ListLIBQUAL_Comments">
	<CFSET COMPAREHEADER = #Evaluate("#FIELDNAME#")#>
	<CFIF REPORTHEADER NEQ #COMPAREHEADER#>
		<CFIF #RECCOUNT# GT 0>
			<CFSET RECORDPERCENT = ((#RECCOUNT#/2048)*100)>
		<TR>
			<TD ALIGN="LEFT">#REPORTHEADER#</td>
			<TD ALIGN="RIGHT">#RECCOUNT#</td>
			<TD ALIGN="RIGHT">
				#NUMBERFORMAT(RECORDPERCENT, '__.__')#%
				<CFSET RECCOUNT = 0>
				<CFSET RECORDPERCENT = 0>
				<CFSET REPORTHEADER = #COMPAREHEADER#>
			</td>
		</TR>
		</CFIF>
	</CFIF>
	<CFSET RECCOUNT = #RECCOUNT# + 1>
</cfloop>
	</CFOUTPUT>
</CFIF>

<cfoutput>
	<CFSET RECORDPERCENT = ((#RECCOUNT#/2048)*100)>
		<TR>
			<TD ALIGN="LEFT">#REPORTHEADER#</td>
			<TD ALIGN="RIGHT">#RECCOUNT#</td>
			<TD ALIGN="RIGHT">#NUMBERFORMAT(RECORDPERCENT, '__.__')#%</td>
		</TR>

		<tr>
			<td ALIGN="CENTER" COLSPAN="3"><HR SIZE="5" NOSHADE /></td>
		</tr>
	<CFIF FORM.REPORTCHOICE LT 3>
		<tr>
			<th ALIGN="CENTER" COLSPAN="3"><H4>#TOTRECCOUNT# LibQual Comment records were selected.</h4></th>
		</tr>
	<CFELSE>
		<tr>
			<th ALIGN="CENTER" COLSPAN="3"><H4>#ListLIBQUAL_Comments.RecordCount# LibQual Comment records were selected.</h4></th>
		</tr>
	</CFIF>
		<TR>
			<TD COLSPAN="8">&nbsp;&nbsp;</TD>
		</TR>
		<tr>
<cfform action="/#application.type#apps/libqual/lqrptslookup.cfm?TYPE=#URL.TYPE#" METHOD="POST">
			<td align="left"><input type="submit" value="CANCEL" tabindex="2" /></td>
</cfform>
		</tr>
		<TR>
			<TD align="left" COLSPAN="3"><CFINCLUDE TEMPLATE="/include/coldfusion/footer.cfm"></TD>
		</TR>
	</table>
</cfoutput>