<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--- Program: processkeyrequestinfo.cfm --->
<!--- By: JOHN R. PASTORI --->
<!--- Date Written: 02/10/2012 --->
<!--- Date in Production: 02/10/2012 --->
<!--- Module: Process Information to Facilities - Key Requests --->
<!-- Last modified by John R. Pastori on 02/10/2012 using ColdFusion Studio. -->

<CFINCLUDE template = "../programsecuritycheck.cfm">

<HTML>
<HEAD>
	<TITLE>Process Information to Facilities - Key Requests</TITLE>
</HEAD>

<BODY>

<CFOUTPUT>
<CFINCLUDE template="/include/coldfusion/formheader.cfm">
<CFIF FORM.PROCESSKEYREQUESTINFO EQ "ADD" OR FORM.PROCESSKEYREQUESTINFO EQ "MODIFY">
	
	<CFIF NOT IsDefined('session.KEYCOUNTER')OR session.KEYCOUNTER EQ 0>
		<CFSET session.KEYCOUNTER = 1>
		<CFSET session.NUMKEYSNEEDED = #FORM.NUMKEYSNEEDED#>
	</CFIF>
	<CFIF FORM.OTHERWEEKDAYFROMHOURS NEQ "">
		<CFSET OTHERWEEKDAYTIMESFROM = '#TimeFormat(FORM.OTHERWEEKDAYFROMHOURS, "hh")#:#FORM.OTHERWEEKDAYFROMMINUTES#:00 #FORM.OTHERWEEKDAYFROMAMPM#'>
		<CFSET OTHERWEEKDAYTIMESTHRU = '#TimeFormat(FORM.OTHERWEEKDAYTHRUHOURS, "hh")#:#FORM.OTHERWEEKDAYTHRUMINUTES#:00 #FORM.OTHERWEEKDAYTHRUAMPM#'>
		<!--- <CFSET FORMATOTHERWEEKDAYTIMESFROM = TimeFormat(OTHERWEEKDAYTIMESFROM, "hh:mm:ss tt")>
		<CFSET FORMATOTHERWEEKDAYTIMESTHRU = TimeFormat(OTHERWEEKDAYTIMESTHRU, "hh:mm:ss tt")> --->
	</CFIF>

	<CFIF FORM.OTHERWEEKENDFROMHOURS NEQ "">
		<CFSET OTHERWEEKENDTIMESFROM = '#TimeFormat(FORM.OTHERWEEKENDFROMHOURS, "hh")#:#FORM.OTHERWEEKENDFROMMINUTES#:00 #FORM.OTHERWEEKENDFROMAMPM#'>
		<CFSET OTHERWEEKENDTIMESTHRU = '#TimeFormat(FORM.OTHERWEEKENDTHRUHOURS, "hh")#:#FORM.OTHERWEEKENDTHRUMINUTES#:00 #FORM.OTHERWEEKENDTHRUAMPM#'>
		<!--- <CFSET FORMATOTHERWEEKENDTIMESFROM = TimeFormat(OTHERWEEKENDTIMESFROM, "hh:mm:ss tt")>
		<CFSET FORMATOTHERWEEKENDTIMESTHRU = TimeFormat(OTHERWEEKENDTIMESTHRU, "hh:mm:ss tt")> --->
	</CFIF>

	<CFIF IsDefined('FORM.RECEIVEDBYCUSTOMER') AND #FORM.RECEIVEDBYCUSTOMER# EQ "YES" AND #FORM.RECEIVEDBYDATE# NEQ "">
		<CFSET FORMATRECEIVEDBYDATE = DateFormat(FORM.RECEIVEDBYDATE, "dd-mmm-yyyy")>
	</CFIF>
	<CFSET FORMATCURRENDATE = DateFormat(NOW(), "dd-mmm-yyyy")>
	<CFSET FORMATCURRENTTIME = TimeFormat(#NOW()#, "HH:mm:ss")>
	
	<CFQUERY name="UpdateKeyRequestInfo" datasource="#application.type#FACILITIES">
		UPDATE	KEYREQUESTS
		SET		KEYTYPEID = #val(FORM.KEYTYPEID)#,
				KEYNUMBER = '#FORM.KEYNUMBER#',
				HOOKNUMBER = '#FORM.HOOKNUMBER#',
			<CFIF IsDefined('FORM.DOORSACCESSED')>
				DOORSACCESSED = '#FORM.DOORSACCESSED#',
			</CFIF>
				DAYSACCESSED = '#FORM.DAYSACCESSED#',
				TIMESACCESSED = '#FORM.TIMESACCESSED#',
			<CFIF IsDefined('FORM.DAYSOTHER')>
				OTHERDAYS = '#FORM.OTHERDAYS#',
			</CFIF>
			<CFIF #FORM.OTHERWEEKDAYFROMHOURS# NEQ "">
				OTHERWEEKDAYTIMESFROM = TO_DATE('#FORMATCURRENDATE# #OTHERWEEKDAYTIMESFROM#', 'DD-MON-YYYY HH:MI:SS AM'),
				OTHERWEEKDAYTIMESTHRU = TO_DATE('#FORMATCURRENDATE# #OTHERWEEKDAYTIMESTHRU#', 'DD-MON-YYYY HH:MI:SS AM'),
			</CFIF>
			<CFIF #FORM.OTHERWEEKENDFROMHOURS# NEQ "">
				OTHERWEEKENDTIMESFROM = TO_DATE('#FORMATCURRENDATE# #OTHERWEEKENDTIMESFROM#', 'DD-MON-YYYY HH:MI:SS AM'),
				OTHERWEEKENDTIMESTHRU = TO_DATE('#FORMATCURRENDATE# #OTHERWEEKENDTIMESTHRU#', 'DD-MON-YYYY HH:MI:SS AM'),
			</CFIF>
				ACCESSENDDATE = TO_DATE('#FORM.ACCESSENDDATE# #FORMATCURRENTTIME#', 'DD-MON-YYYY HH24:MI:SS'),
				DISPOSITION = '#FORM.DISPOSITION#',
				NUMBERREPLACED = '#FORM.NUMBERREPLACED#',
		<CFIF IsDefined('FORM.RECEIVEDBYCUSTOMER')>
				RECEIVEDBYCUSTOMER = '#FORM.RECEIVEDBYCUSTOMER#',
			<CFIF #FORM.RECEIVEDBYCUSTOMER# EQ "YES" AND #FORM.RECEIVEDBYDATE# NEQ "" >
				RECEIVEDBYDATE = TO_DATE('#FORMATRECEIVEDBYDATE# #FORMATCURRENTTIME#', 'DD-MON-YYYY HH24:MI:SS'),
			</CFIF>
		</CFIF>
				REPLACEDREASON = '#FORM.REPLACEDREASON#'
		WHERE	(KEYREQUESTID = #val(Cookie.KEYREQUESTID)#)
	</CFQUERY>

	<CFIF FORM.PROCESSKEYREQUESTINFO EQ "ADD">

		<A href="/"><IMG src="/images/bigheader.jpg" width="279" height="63" alt="LFOLKS Intranet Web Site" align="left" VALIGN="top" border="0" /></A>
		<BR /><BR /><BR /><BR /><BR />
		<H1>Data ADDED!</H1>
	<CFELSE>
		<H1>Data MODIFIED!</H1>
	</CFIF>
	<CFIF #session.KEYCOUNTER# LT #session.NUMKEYSNEEDED#>
		<CFSET session.KEYCOUNTER = session.KEYCOUNTER +1>
		<META http-equiv="Refresh" content="1; URL=/#application.type#apps/facilities/keyrequestinfo.cfm?PROCESS=#FORM.PROCESSKEYREQUESTINFO#" />
	<CFELSE>
		<CFSET session.KEYCOUNTER = 0>
		<CFSET session.NUMKEYSNEEDED = 0>
		<META http-equiv="Refresh" content="1; URL=/#application.type#apps/facilities/workrequest.cfm?PROCESS=#FORM.PROCESSKEYREQUESTINFO#" />
	</CFIF>

</CFIF>

<CFIF FORM.PROCESSKEYREQUESTINFO EQ "DELETE" OR FORM.PROCESSKEYREQUESTINFO EQ "CANCELADD">
	
	<CFQUERY name="DeleteKeyRequestInfo" datasource="#application.type#FACILITIES">
		DELETE FROM 	KEYREQUESTS
		WHERE 		KEYREQUESTID = #val(Cookie.KEYREQUESTID)#
	</CFQUERY> 
	<H1>Data DELETED!</H1>
	<CFIF FORM.PROCESSKEYREQUESTINFO EQ "DELETE">
		<META http-equiv="Refresh" content="1; URL=/#application.type#apps/facilities/keyrequestinfo.cfm?PROCESS=MODIFYDELETE" />
	<CFELSE>
		<META http-equiv="Refresh" content="1; URL=/#application.type#apps/facilities/workrequest.cfm?PROCESS=MODIFYDELETE" />
	</CFIF>
</CFIF>
</CFOUTPUT>

</BODY>
</HTML>