<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!--- Program: processconfigmgmtrequests.cfm --->
<!--- By: JOHN R. PASTORI --->
<!--- Date Written: 01/23/2009 --->
<!--- Date in Production: 01/23/2009 --->
<!--- Module: Process Information to IDT Configuration Management - Requests --->
<!-- Last modified by John R. Pastori on 01/23/2009 using ColdFusion Studio. -->

<HTML>
<HEAD>
	<TITLE>Process Information to IDT Configuration Management - Requests </TITLE>
</HEAD>

<BODY>

<CFOUTPUT>
<CFINCLUDE template="/include/coldfusion/formheader.cfm">
<CFIF FORM.PROCESSCMREQUESTS EQ "ADD" OR FORM.PROCESSCMREQUESTS EQ "MODIFY">
	<CFSET FORMATREQUESTDATE = #DateFormat(FORM.REQUESTDATE, 'dd-mmm-yyyy')#>
	<CFIF IsDefined('FORM.AUTHORIZATIONDATE') AND NOT #FORM.AUTHORIZATIONDATE# EQ "">
		<CFSET FORMATAUTHORIZATIONDATE = #DateFormat(FORM.AUTHORIZATIONDATE, 'dd-mmm-yyyy')#>
	</CFIF>
	<CFIF IsDefined('FORM.NOTIFICATIONDATE') AND NOT #FORM.NOTIFICATIONDATE# EQ "">
		<CFSET FORMATNOTIFICATIONDATE = #DateFormat(FORM.NOTIFICATIONDATE, 'dd-mmm-yyyy')#>
	</CFIF>
	<CFIF IsDefined('FORM.FOLLOWUPDATE_1ST') AND NOT #FORM.FOLLOWUPDATE_1ST# EQ "">
		<CFSET FORMATFOLLOWUPDATE_1ST = #DateFormat(FORM.FOLLOWUPDATE_1ST, 'dd-mmm-yyyy')#>
	</CFIF>
	<CFIF IsDefined('FORM.FOLLOWUPDATE_2ND') AND NOT #FORM.FOLLOWUPDATE_2ND# EQ "">
		<CFSET FORMATFOLLOWUPDATE_2ND = #DateFormat(FORM.FOLLOWUPDATE_2ND, 'dd-mmm-yyyy')#>
	</CFIF>
	<CFIF IsDefined('FORM.BACKUPDATE') AND NOT #FORM.BACKUPDATE# EQ "">
		<CFSET FORMATBACKUPDATE = #DateFormat(FORM.BACKUPDATE, 'dd-mmm-yyyy')#>
	</CFIF>
	<CFIF IsDefined('FORM.CHANGEDATE') AND NOT #FORM.CHANGEDATE# EQ "">
		<CFSET FORMATCHANGEDATE = #DateFormat(FORM.CHANGEDATE, 'dd-mmm-yyyy')#>
	</CFIF>
	<CFIF IsDefined('FORM.CHANGETIME') AND NOT #FORM.CHANGETIME# EQ "">
		<CFSET FORMATCHANGETIME = #TimeFormat(FORM.CHANGETIME, 'hh:mm:ss tt')#>
	</CFIF>
	<CFIF IsDefined('FORM.AVAILABILITYDATE') AND NOT #FORM.AVAILABILITYDATE# EQ "">
		<CFSET FORMATAVAILABILITYDATE = #DateFormat(FORM.AVAILABILITYDATE, 'dd-mmm-yyyy')#>
	</CFIF>
	<CFSET FORMATMODIFIEDDATE = #DateFormat(FORM.MODIFIEDDATE, 'dd-mmm-yyyy')#>

	<CFQUERY name="UpdateCMRequests" datasource="#application.type#CONFIGMGMT">
		UPDATE	CONFIGMGMTREQUESTS
		SET		SYSTEM = UPPER('#FORM.SYSTEM#'),
				REQUESTERID = #val(FORM.REQUESTERID)#,
				REQUESTDATE = TO_DATE('#FORMATREQUESTDATE#', 'DD-MON-YYYY'),
				CHANGEDESCRIPTION = '#FORM.CHANGEDESCRIPTION#',
				CHANGEJUSTIFICATION = '#FORM.CHANGEJUSTIFICATION#',
				AUTHORIZERID = #val(FORM.AUTHORIZERID)#,
			<CFIF IsDefined('FORM.AUTHORIZATIONDATE') AND NOT #FORM.AUTHORIZATIONDATE# EQ "">
				AUTHORIZATIONDATE = TO_DATE('#FORMATAUTHORIZATIONDATE#', 'DD-MON-YYYY'),
			</CFIF>
				SERVERADMCOMMENTS = '#FORM.SERVERADMCOMMENTS#',
				CHANGESCHEDULED = '#FORM.CHANGESCHEDULED#',
				NOTIFICATIONDESCRIPTION = '#FORM.NOTIFICATIONDESCRIPTION#',
				NOTIFIERID = #val(FORM.NOTIFIERID)#,
			<CFIF IsDefined('FORM.NOTIFICATIONDATE') AND NOT #FORM.NOTIFICATIONDATE# EQ "">
				NOTIFICATIONDATE = TO_DATE('#FORMATNOTIFICATIONDATE#', 'DD-MON-YYYY'),
			</CFIF>
				FOLLOWUPDESCRIPTION_1ST = '#FORM.FOLLOWUPDESCRIPTION_1ST#',
				FOLLOWUPNOTIFIERID_1ST = #val(FORM.FOLLOWUPNOTIFIERID_1ST)#,
			<CFIF IsDefined('FORM.FOLLOWUPDATE_1ST') AND NOT #FORM.FOLLOWUPDATE_1ST# EQ "">
				FOLLOWUPDATE_1ST = TO_DATE('#FORMATFOLLOWUPDATE_1ST#', 'DD-MON-YYYY'),
			</CFIF>
				FOLLOWUPDESCRIPTION_2ND = '#FORM.FOLLOWUPDESCRIPTION_2ND#',
				FOLLOWUPNOTIFIERID_2ND = #val(FORM.FOLLOWUPNOTIFIERID_2ND)#,
			<CFIF IsDefined('FORM.FOLLOWUPDATE_2ND') AND NOT #FORM.FOLLOWUPDATE_2ND# EQ "">
				FOLLOWUPDATE_2ND = TO_DATE('#FORMATFOLLOWUPDATE_2ND#', 'DD-MON-YYYY'),
			</CFIF>
			<CFIF IsDefined('FORM.BACKUPDATE') AND NOT #FORM.BACKUPDATE# EQ "">
				BACKUPDATE = TO_DATE('#FORMATBACKUPDATE#', 'DD-MON-YYYY'),
			</CFIF>
				IMPLEMENTERID = #val(FORM.IMPLEMENTERID)#,
			<CFIF IsDefined('FORM.CHANGEDATE') AND NOT #FORM.CHANGEDATE# EQ "">
				CHANGEDATE = TO_DATE('#FORMATCHANGEDATE#', 'DD-MON-YYYY'),
			</CFIF>
			<CFIF IsDefined('FORM.CHANGETIME') AND NOT #FORM.CHANGETIME# EQ "">
				CHANGETIME = TO_DATE('#FORMATCHANGEDATE#, #FORMATCHANGETIME#', 'DD-MON-YYYY, HH:MI:SS AM'),
			</CFIF>
				IMPLEMENTATIONDESCRIPTION = '#FORM.IMPLEMENTATIONDESCRIPTION#',
				TESTINGMONITORDESCRIPTION = '#FORM.TESTINGMONITORDESCRIPTION#',
				CHANGESTATUS = '#FORM.CHANGESTATUS#',
				AVAILABILITYDESCRIPTION = '#FORM.AVAILABILITYDESCRIPTION#',
				AVAILABILITYNOTIFIERID = #val(FORM.AVAILABILITYNOTIFIERID)#,
			<CFIF IsDefined('FORM.AVAILABILITYDATE') AND NOT #FORM.AVAILABILITYDATE# EQ "">
				AVAILABILITYDATE = TO_DATE('#FORMATAVAILABILITYDATE#', 'DD-MON-YYYY'),
			</CFIF>
				MODIFIEDBYID = #val(FORM.MODIFIEDBYID)#,
				MODIFIEDDATE = TO_DATE('#FORMATMODIFIEDDATE#', 'DD-MON-YYYY')
		WHERE	CONFIGMGMTREQUESTID = #val(Cookie.CONFIGMGMTREQUESTID)#
	</CFQUERY>

	<CFIF FORM.PROCESSCMREQUESTS EQ "ADD">
		<H1>Data ADDED!</H1>
		<META http-equiv="Refresh" content="0; URL=/#application.type#apps/configmgmt/configmgmtrequests.cfm?PROCESS=ADD" />
	<CFELSE>
		<H1>Data MODIFIED!</H1>
		<META http-equiv="Refresh" content="0; URL=/#application.type#apps/configmgmt/configmgmtrequests.cfm?PROCESS=MODIFYDELETE" />
	</CFIF>
</CFIF>

<CFIF FORM.PROCESSCMREQUESTS EQ "DELETE" OR FORM.PROCESSCMREQUESTS EQ "CANCELADD">
	<CFQUERY name="DeleteCMRequests" datasource="#application.type#CONFIGMGMT">
		DELETE FROM	CONFIGMGMTREQUESTS
		WHERE		CONFIGMGMTREQUESTID = #val(Cookie.CONFIGMGMTREQUESTID)#
	</CFQUERY> 
	<H1>Configuration Management Data DELETED!</H1>
	<CFIF FORM.PROCESSCMREQUESTS EQ "DELETE">
		<META http-equiv="Refresh" content="0; URL=/#application.type#apps/configmgmt/configmgmtrequests.cfm?PROCESS=MODIFYDELETE" />
	<CFELSE>
		<META http-equiv="Refresh" content="0; URL=#Cookie.INDEXDIR#/index.cfm" />
		<CFEXIT>
	</CFIF>
</CFIF>
</CFOUTPUT>

</BODY>
</HTML>